[[redirects]]
  from = "https://calebetaylor.com"
  to = "https://calebtaylor.dev"
  status = 301
  force = true

[[redirects]]
  from = "www.calebetaylor.com"
  to = "www.calebtaylor.dev"
  status = 301
  force = true